const statesData = {
    "IN-AN": {
        name: "Andaman and Nicobar Islands",
        capital: "Port Blair",
        language: "Hindi, English, Bengali",
        food: "Seafood, Fish Curry, Coconut dishes",
        places: "Radhanagar Beach, Cellular Jail, Ross Island",
        culture: "Indigenous Tribal Culture, Sea Festivals",
        history: "Historically served as a naval base for the Marathas and later as a penal colony (Kalapani) during British rule.",
        specialties: "Shell crafts, pearl jewelry, and woodwork.",
        traditions: "Tribal festivals and the Island Tourism Festival.",
        clothing: "Light cotton wear due to the tropical climate, while indigenous tribes maintain their traditional minimal attire."
    },
    "IN-AP": {
        name: "Andhra Pradesh",
        capital: "Amaravati",
        language: "Telugu",
        food: "Pulihora, Gongura Pachadi, Hyderabadi Biryani",
        places: "Tirupati, Araku Valley, Belum Caves",
        culture: "Kuchipudi Dance, Sankranti Festival",
        history: "An ancient region ruled by the Satavahanas and Pallavas, known for its rich Buddhist heritage and powerful empires.",
        specialties: "Kondapalli toys, Kalamkari paintings, and Tirupati Laddu.",
        traditions: "Kuchipudi classical dance and vibrant Sankranti harvest celebrations.",
        clothing: "Men usually wear a dhoti and kurta, while women wear intricately woven sarees like Dharmavaram and Mangalagiri."
    },
    "IN-AR": {
        name: "Arunachal Pradesh",
        capital: "Itanagar",
        language: "English, Nishi, Monpa",
        food: "Thukpa, Apong (Rice Beer), Bamboo Shoot",
        places: "Tawang Monastery, Ziro Valley, Namdapha",
        culture: "Losar Festival, Monpa Tribe Traditions",
        history: "Known as the 'Land of the Dawn-Lit Mountains,' it has strong historical ties to Tibet and ancient trade routes.",
        specialties: "Bamboo and cane crafts, weaving, and Thangka paintings.",
        traditions: "Losar (New Year) and agriculture-based tribal festivals.",
        clothing: "Wraparound skirts and full-sleeved jackets for women, with distinctive tribal headgears made of cane."
    },
    "IN-AS": {
        name: "Assam",
        capital: "Dispur",
        language: "Assamese",
        food: "Masor Tenga, Pitha, Assam Tea",
        places: "Kaziranga National Park, Majuli Island",
        culture: "Bihu Dance, Satriya, Ambubachi Mela",
        history: "Ruled by the mighty Ahom Dynasty for 600 years, successfully resisting the Mughal expansion into Northeast India.",
        specialties: "Muga silk (golden silk), Assam tea, and brass metal crafts.",
        traditions: "Bihu festival celebrating the harvest season with energetic dance and music.",
        clothing: "Women wear the traditional Mekhela Chador, while men wear a suria (dhoti) and a gamosa."
    },
    "IN-BR": {
        name: "Bihar",
        capital: "Patna",
        language: "Hindi, Bhojpuri, Maithili",
        food: "Litti Chokha, Sattu, Khaja",
        places: "Bodh Gaya, Nalanda University, Mahabodhi Temple",
        culture: "Chhath Puja, Madhubani Art",
        history: "The birthplace of Buddhism and Jainism, and the center of the powerful Maurya and Gupta empires.",
        specialties: "Madhubani paintings, Bhagalpuri silk, and stone pottery.",
        traditions: "Chhath Puja, a rigorous ancient Hindu festival dedicated to the Sun God.",
        clothing: "Men traditionally wear dhoti-kurta, while women wear sarees, often styled in the regional 'Seedha Pallu' drape."
    },
    "IN-CH": {
        name: "Chandigarh",
        capital: "Chandigarh",
        language: "Punjabi, Hindi, English",
        food: "Chole Bhature, Butter Chicken",
        places: "Rock Garden, Sukhna Lake, Rose Garden",
        culture: "Baisakhi, Modern Architecture Heritage",
        history: "A post-independence planned city designed by Swiss-French architect Le Corbusier, serving as the capital for two states.",
        specialties: "Urban design, Phulkari suits from the surrounding region, and woodcraft.",
        traditions: "A cosmopolitan blend of Punjabi and Haryanvi traditions with modern urban culture.",
        clothing: "A mix of modern western wear and traditional Punjabi attire like Salwar Kameez."
    },
    "IN-CT": {
        name: "Chhattisgarh",
        capital: "Raipur",
        language: "Chhattisgarhi, Hindi",
        food: "Muthia, Chila, Fara",
        places: "Chitrakote Falls, Bastar, Tirathgarh",
        culture: "Bastar Dussehra, Panthi Dance, Tribal Arts",
        history: "Historically known as Dakshin Kosala, it has a rich tribal history and was a key route in the Ramayana epic.",
        specialties: "Bell metal (Dhokra) art, terracotta, and Kosa silk.",
        traditions: "Bastar Dussehra, a unique 75-day tribal festival, and traditional Panthi folk dance.",
        clothing: "Women wear Lugda (saree) and Polkha (blouse), while tribal groups have distinct, vibrant ceremonial attire."
    },
    "IN-DD": {
        name: "Daman and Diu",
        capital: "Daman",
        language: "Gujarati, Hindi, Portuguese",
        food: "Seafood, Rotla, Jetty Roll",
        places: "Diu Fort, Jampore Beach, St. Paul's Church",
        culture: "Portuguese Heritage, Nariyal Purnima",
        history: "A former Portuguese colony for over 400 years, finally incorporated into India in 1961.",
        specialties: "Tortoise shell crafts, mat weaving, and Portuguese-style architecture.",
        traditions: "A unique blend of Indian festivals like Garba mixed with European carnival traditions.",
        clothing: "A mix of traditional Gujarati clothing and western seaside wear."
    },
    "IN-DL": {
        name: "Delhi",
        capital: "New Delhi",
        language: "Hindi, Punjabi, Urdu",
        food: "Chole Bhature, Butter Chicken, Chaat",
        places: "Red Fort, India Gate, Qutub Minar",
        culture: "Republic Day Parade, Diwali, Historic Architecture",
        history: "A historic capital rebuilt seven times, shaped prominently by the Delhi Sultanate, Mughals, and British Empire.",
        specialties: "Zardozi work, Meenakari, and vibrant street food culture from Chandni Chowk.",
        traditions: "A melting pot of cultures, celebrating all major Indian festivals with massive scale, especially Diwali and Eid.",
        clothing: "Highly cosmopolitan; people wear everything from trendy western fashion to traditional Salwar suits and Kurtas."
    },
    "IN-DN": {
        name: "Dadra and Nagar Haveli",
        capital: "Silvassa",
        language: "Gujarati, Hindi",
        food: "Ubadiyu, Khaman",
        places: "Dudhni Lake, Vanganga Lake Garden",
        culture: "Tarpa Dance, Tribal Festivals",
        history: "Ruled by the Marathas and later the Portuguese until its liberation in 1954.",
        specialties: "Bamboo crafts, leather woodwork, and Warli paintings.",
        traditions: "Tarpa and Bhavada dances performed by the indigenous Warli and Kokna tribes.",
        clothing: "Tribal women often wear a knee-length lugden, while men wear a loincloth and a waistcoat."
    },
    "IN-GA": {
        name: "Goa",
        capital: "Panaji",
        language: "Konkani",
        food: "Fish Curry Rice, Bebinca, Vindaloo",
        places: "Baga Beach, Dudhsagar Falls, Basilica of Bom Jesus",
        culture: "Goa Carnival, Shigmo, Portuguese Influence",
        history: "A major trade hub ruled by the Kadambas, later becoming the capital of the Portuguese Empire in the East.",
        specialties: "Azulejos (painted tiles), cashew feni, and sea-shell crafts.",
        traditions: "The vibrant Goa Carnival, Shigmo festival, and a strong culture of music and football.",
        clothing: "Coastal and western wear are common, while traditional Catholic women wear dresses and Hindu women wear a 9-yard Navvari."
    },
    "IN-GJ": {
        name: "Gujarat",
        capital: "Gandhinagar",
        language: "Gujarati",
        food: "Dhokla, Thepla, Fafda",
        places: "Statue of Unity, Rann of Kutch, Gir National Park",
        culture: "Navratri, Garba, Kite Festival",
        history: "Home to ancient Indus Valley Civilization sites and an important historical hub for global maritime trade.",
        specialties: "Kutch embroidery, Bandhani sarees, and Patola weaving.",
        traditions: "The energetic Garba and Dandiya dances during the 9-day Navratri festival, and the International Kite Festival.",
        clothing: "Men traditionally wear Chrono and Kediyu, women wear Chaniya Choli heavily embellished with mirror work."
    },
    "IN-HP": {
        name: "Himachal Pradesh",
        capital: "Shimla",
        language: "Hindi, Pahari",
        food: "Madra, Dham, Babru",
        places: "Manali, Rohtang Pass, Spiti Valley",
        culture: "Kullu Dussehra, Nati Dance",
        history: "Known as 'Dev Bhoomi' (Land of Gods), it was historically divided into several small hill kingdoms before British integration.",
        specialties: "Kullu shawls, Chamba caps, and Tibetan carpets.",
        traditions: "The week-long Kullu Dussehra and the traditional Nati folk dance.",
        clothing: "Men wear Chola and a distinctive Himachali cap (Topi), while women wear long woolen dresses called Pattus."
    },
    "IN-HR": {
        name: "Haryana",
        capital: "Chandigarh",
        language: "Hindi, Haryanvi",
        food: "Bajre Ki Roti, Kadhi Pakora, Kachri",
        places: "Kurukshetra, Sultanpur Bird Sanctuary",
        culture: "Surajkund Crafts Mela, Phag Dance",
        history: "The site of the epic Mahabharata war at Kurukshetra and three pivotal battles at Panipat that shaped Indian history.",
        specialties: "Phulkari embroidery, woven mudhas (stools), and brassware.",
        traditions: "Phag and Saang dances, alongside a strong agrarian lifestyle and wrestling culture.",
        clothing: "Men wear Dhoti-Kurta with a Pagri (turban), women wear a Daman (long skirt), Kurti, and Chunder."
    },
    "IN-JH": {
        name: "Jharkhand",
        capital: "Ranchi",
        language: "Hindi, Santhali",
        food: "Dhuska, Rugra, Handia",
        places: "Hundru Falls, Betla National Park, Deoghar",
        culture: "Sarhul, Karma Festival, Tribal Woodwork",
        history: "Known as the 'Land of Forests', it has a deep-rooted tribal history with heroes like Birsa Munda who fought British rule.",
        specialties: "Paitkar paintings, bamboo works, and Dokra metal crafts.",
        traditions: "Nature-worshipping festivals like Sarhul and Karma, featuring rhythmic tribal drumming and dancing.",
        clothing: "Tribal women wear Santhali sarees (Panchi and Parhan), often paired with heavy silver jewelry."
    },
    "IN-JK": {
        name: "Jammu and Kashmir",
        capital: "Srinagar (Summer), Jammu (Winter)",
        language: "Kashmiri, Dogri, Urdu",
        food: "Rogan Josh, Wazwan, Kahwa",
        places: "Dal Lake, Gulmarg, Vaishno Devi",
        culture: "Shikara Culture, Rouf Dance",
        history: "A historically vital region on the Silk Road, renowned for its beautiful Mughal gardens and ancient Hindu shrines.",
        specialties: "Pashmina shawls, walnut wood carving, and paper-mache crafts.",
        traditions: "The preparation of the royal Wazwan feast and traditional Rouf folk dance.",
        clothing: "Both men and women wear the Phiran (a long woolen cloak), often accompanied by a Taranga headress for women."
    },
    "IN-KA": {
        name: "Karnataka",
        capital: "Bengaluru",
        language: "Kannada",
        food: "Bisi Bele Bath, Neer Dosa, Mysore Pak",
        places: "Mysore Palace, Hampi, Coorg",
        culture: "Yakshagana, Dasara Festival",
        history: "Ruled by powerful empires like the Chalukyas, Hoysalas, and Vijayanagara, leaving behind incredible stone temples.",
        specialties: "Mysore silk, sandalwood carvings, and Bidriware.",
        traditions: "The grand Mysore Dasara elephant procession and theatrical Yakshagana performances.",
        clothing: "Women wear the Ilkal or Mysore silk saree, while men wear a Panche (dhoti) and a Mysore Peta (turban)."
    },
    "IN-KL": {
        name: "Kerala",
        capital: "Thiruvananthapuram",
        language: "Malayalam",
        food: "Appam, Kerala Fish Curry, Puttu",
        places: "Munnar, Alleppey Backwaters, Wayanad",
        culture: "Onam, Kathakali, Snake Boat Race",
        history: "A major spice trade center since ancient times, attracting Romans, Arabs, and eventually European colonizers.",
        specialties: "Coir products, mural paintings, and Ayurveda.",
        traditions: "Elaborate Kathakali dance-drama, martial arts like Kalaripayattu, and the Onam harvest festival.",
        clothing: "Traditional wear is white with gold borders; women wear the Kasavu saree or Set Mundu, men wear a Mundu."
    },
    "IN-LD": {
        name: "Lakshadweep",
        capital: "Kavaratti",
        language: "Malayalam, Mahl",
        food: "Tuna Curry, Coconut Rice",
        places: "Agatti Island, Minicoy, Bangaram Atoll",
        culture: "Lava Dance, Marine Festivals",
        history: "Historically influenced by Arab traders and sailors, it was later controlled by the Arakkal kingdom of Kerala.",
        specialties: "Coir making, seashell crafts, and boat building.",
        traditions: "Folk dances like Lava and Kolkali, heavily influenced by Islamic and Maldivian culture.",
        clothing: "Men wear a lungi with a shirt, while women wear a traditional Libus (a long dress with a head covering)."
    },
    "IN-MH": {
        name: "Maharashtra",
        capital: "Mumbai",
        language: "Marathi",
        food: "Vada Pav, Misal Pav, Puran Poli",
        places: "Gateway of India, Ajanta Caves, Mahabaleshwar",
        culture: "Ganesh Chaturthi, Lavani Dance",
        history: "Defined by the mighty Maratha Empire founded by Chhatrapati Shivaji Maharaj in the 17th century, featuring strong naval and hill forts.",
        specialties: "Warli tribal paintings, Kolhapuri chappals, and Paithani silk sarees.",
        traditions: "Powada storytelling, massive Ganesh Chaturthi processions, and Dahi Handi.",
        clothing: "Men wear a dhoti and pheta (turban), while women traditionally wear the nine-yard Nauvari saree."
    },
    "IN-ML": {
        name: "Meghalaya",
        capital: "Shillong",
        language: "English, Khasi, Garo",
        food: "Jadoh, Pumaloi, Bamboo Shoots",
        places: "Cherrapunji, Living Root Bridges, Dawki",
        culture: "Wangala Festival, Nongkrem Dance",
        history: "Known as the 'Abode of Clouds', it is home to ancient matrilineal tribes who have inhabited the hills for centuries.",
        specialties: "Cane and bamboo products, Endi silk, and wood carving.",
        traditions: "The Wangala (100 drums) festival and strong matrilineal societal structures.",
        clothing: "Khasi women wear the Jainsem and Dhara, while Garo women wear the Dakmanda."
    },
    "IN-MN": {
        name: "Manipur",
        capital: "Imphal",
        language: "Manipuri (Meitei)",
        food: "Eromba, Chamthong, Kangshoi",
        places: "Loktak Lake, Kangla Fort, Dzukou Valley",
        culture: "Yaoshang, Ras Lila (Manipuri Dance)",
        history: "An ancient princely state that was the site of significant battles during World War II, including the Battle of Imphal.",
        specialties: "Black stone pottery (Longpi), handloom textiles, and cane work.",
        traditions: "The classical Ras Lila dance and traditional sports like Sagol Kangjei (the origin of modern polo).",
        clothing: "Women wear the Innaphi (shawl) and Phanek (skirt), while men wear a dhoti with a traditional jacket."
    },
    "IN-MP": {
        name: "Madhya Pradesh",
        capital: "Bhopal",
        language: "Hindi",
        food: "Poha, Jalebi, Bhutte Ka Kees",
        places: "Khajuraho, Bandhavgarh, Sanchi Stupa",
        culture: "Khajuraho Dance Festival, Bhagoria",
        history: "The heart of India, historically ruled by the Mauryas, Guptas, and Marathas, boasting incredible ancient rock shelters at Bhimbetka.",
        specialties: "Chanderi and Maheshwari silk sarees, and Gond tribal art.",
        traditions: "The classical Khajuraho Dance Festival and the tribal Bhagoria Haat.",
        clothing: "Women traditionally wear Lehenga and Choli with an Odhni, while men wear Dhoti, Safa (turban), and Bandi (jacket)."
    },
    "IN-MZ": {
        name: "Mizoram",
        capital: "Aizawl",
        language: "Mizo, English",
        food: "Bai, Vawksa Rep, Bamboo Shoot",
        places: "Phawngpui, Vantawng Falls, Reiek",
        culture: "Chapchar Kut, Cheraw (Bamboo Dance)",
        history: "A highly literate state with a history of tribal migrations, formally becoming a full Indian state in 1987.",
        specialties: "Intricate cane and bamboo work, and traditional Mizo puan (weaving).",
        traditions: "The famous Cheraw (bamboo dance) and the spring festival of Chapchar Kut.",
        clothing: "Women wear the Puan (a beautifully woven wraparound skirt), often with a Kawrchei (blouse)."
    },
    "IN-NL": {
        name: "Nagaland",
        capital: "Kohima",
        language: "English, Nagamese",
        food: "Smoked Pork, Bamboo Shoot, Akhuni",
        places: "Hornbill Festival, Dzukou Valley, Kohima War Cemetery",
        culture: "Hornbill Festival, Rich Tribal Heritage",
        history: "Home to diverse Naga warrior tribes, and the site of the famous Battle of Kohima during WWII.",
        specialties: "Vibrant woven shawls, Naga spears, and tribal beaded jewelry.",
        traditions: "The 'Festival of Festivals' known as the Hornbill Festival, showcasing tribal dances and warrior chants.",
        clothing: "Distinctive tribal shawls (like the Ao or Angami shawls) that denote a person's tribe and social status."
    },
    "IN-OR": {
        name: "Odisha",
        capital: "Bhubaneswar",
        language: "Odia",
        food: "Dalma, Rasagola, Pakhala Bhata",
        places: "Konark Sun Temple, Puri Jagannath Temple, Chilika Lake",
        culture: "Rath Yatra, Odissi Dance",
        history: "Historically known as Kalinga, the site of the massive battle that caused Emperor Ashoka to embrace Buddhism.",
        specialties: "Pattachitra paintings, silver filigree (Tarakasi), and Sambalpuri sarees.",
        traditions: "The massive chariot festival of Rath Yatra in Puri and classical Odissi dance.",
        clothing: "Women wear Ikat or Sambalpuri sarees, while men traditionally wear a Dhoti and Kurta with a Gamucha."
    },
    "IN-PB": {
        name: "Punjab",
        capital: "Chandigarh",
        language: "Punjabi",
        food: "Makki di Roti, Sarson ka Saag, Lassi",
        places: "Golden Temple, Wagah Border, Jallianwala Bagh",
        culture: "Baisakhi, Bhangra and Giddha",
        history: "The 'Land of Five Rivers', it is the birthplace of Sikhism and was a powerful empire under Maharaja Ranjit Singh.",
        specialties: "Phulkari embroidery, Punjabi Juttis, and woodwork.",
        traditions: "High-energy Bhangra and Giddha dances, and the harvest festival of Baisakhi.",
        clothing: "Men wear Kurta-Pajama with a Pagri (turban), while women wear vibrant Salwar Kameez and Patiala suits."
    },
    "IN-PY": {
        name: "Puducherry",
        capital: "Puducherry",
        language: "Tamil, French",
        food: "Quiche, Croissants, Seafood Curry",
        places: "Auroville, Promenade Beach, Paradise Beach",
        culture: "French Colonial Heritage, Bastille Day",
        history: "The largest French colonial settlement in India, deeply influencing the town's architecture and culture until 1954.",
        specialties: "Auroville handmade crafts, pottery, and French-inspired baking.",
        traditions: "A unique blend of South Indian festivals and French celebrations like Bastille Day.",
        clothing: "A mix of traditional Tamil wear (Sarees and Veshtis) alongside modern western and European fashion."
    },
    "IN-RJ": {
        name: "Rajasthan",
        capital: "Jaipur",
        language: "Hindi, Rajasthani",
        food: "Dal Baati Churma, Laal Maas, Ghevar",
        places: "Hawa Mahal, Thar Desert, Udaipur Forts",
        culture: "Ghoomar Dance, Pushkar Camel Fair",
        history: "The land of Rajput kings, known for epic tales of bravery, massive desert forts, and royal palaces.",
        specialties: "Blue pottery, block-printed textiles, and Kundan jewelry.",
        traditions: "Folk music by Manganiyars, Kalbelia dance, and vibrant desert festivals.",
        clothing: "Brightly colored Bandhani odhnis for women and Angrakha with colorful turbans (Paggar) for men."
    },
    "IN-SK": {
        name: "Sikkim",
        capital: "Gangtok",
        language: "Nepali, Sikkimese, Lepcha",
        food: "Momo, Thukpa, Phagshapa",
        places: "Nathu La Pass, Rumtek Monastery, Tsomgo Lake",
        culture: "Losar, Saga Dawa, Mask Dance",
        history: "An independent kingdom ruled by the Chogyals until it integrated with India in 1975, heavily influenced by Tibetan Buddhism.",
        specialties: "Thangka paintings, woven carpets, and wooden carved masks.",
        traditions: "Monastic Cham (mask) dances and Buddhist festivals like Saga Dawa and Losar.",
        clothing: "The traditional Bakhu (or Kho) is worn by both men and women, often paired with a silk blouse (Honju)."
    },
    "IN-TG": {
        name: "Telangana",
        capital: "Hyderabad",
        language: "Telugu, Urdu",
        food: "Hyderabadi Biryani, Haleem, Sakinalu",
        places: "Charminar, Golconda Fort, Ramoji Film City",
        culture: "Bathukamma, Bonalu",
        history: "Ruled by the Kakatiya dynasty and later the Nizams of Hyderabad, creating a rich blend of Persian and South Indian architecture.",
        specialties: "Pochampally Ikat sarees, Bidri craft, and pearl jewelry.",
        traditions: "The floral festival of Bathukamma and the vibrant Bonalu state festival.",
        clothing: "Women wear Pochampally or Gadwal sarees, while men traditionally wear a Pancha (dhoti) and Kurta."
    },
    "IN-TN": {
        name: "Tamil Nadu",
        capital: "Chennai",
        language: "Tamil",
        food: "Idli, Dosa, Chettinad Chicken",
        places: "Meenakshi Temple, Ooty, Mahabalipuram",
        culture: "Pongal, Bharatanatyam",
        history: "Home to the ancient Chola, Chera, and Pandya dynasties, known for creating some of the greatest Dravidian temple architecture in the world.",
        specialties: "Kanchipuram silk sarees, Tanjore paintings, and bronze statues.",
        traditions: "The classical Bharatanatyam dance and the major harvest festival of Pongal.",
        clothing: "Men wear a white Veshti (dhoti) with an Angavastram, while women wear traditional Kanjeevaram silk sarees."
    },
    "IN-TR": {
        name: "Tripura",
        capital: "Agartala",
        language: "Bengali, Kokborok",
        food: "Mui Borok, Chakhwi, Mosdeng",
        places: "Ujjayanta Palace, Neermahal, Unakoti",
        culture: "Kharchi Puja, Hojagiri Dance",
        history: "A former princely state ruled by the Manikya dynasty for centuries before joining the Indian Union in 1949.",
        specialties: "Intricate bamboo and cane handicrafts, and traditional handloom weaving.",
        traditions: "The 14-Gods festival of Kharchi Puja and the balancing Hojagiri folk dance.",
        clothing: "Women wear the Rignai (a wraparound lower garment) and Risa, while men wear a Rikutu (loincloth) and Kamchwlwi borok (shirt)."
    },
    "IN-UP": {
        name: "Uttar Pradesh",
        capital: "Lucknow",
        language: "Hindi, Urdu",
        food: "Tunday Kababi, Chaat, Peda",
        places: "Taj Mahal, Varanasi Ghats, Agra Fort",
        culture: "Kumbh Mela, Kathak Dance",
        history: "The heartland of ancient Indian mythology (Ayodhya, Mathura) and a major center of power for the Mughal Empire.",
        specialties: "Chikankari embroidery from Lucknow, brassware from Moradabad, and Banarasi silk.",
        traditions: "The massive Kumbh Mela gathering, Kathak classical dance, and vibrant Holi celebrations in Barsana.",
        clothing: "Women generally wear sarees or Salwar Kameez, while men wear Dhoti-Kurta or Kurta-Pajama with a topi."
    },
    "IN-UT": {
        name: "Uttarakhand",
        capital: "Dehradun (Winter), Gairsain (Summer)",
        language: "Hindi, Garhwali, Kumaoni",
        food: "Kafuli, Aloo ke Gutke, Bal Mithai",
        places: "Rishikesh, Kedarnath, Nainital",
        culture: "Kumbh Mela, Ganga Aarti, Garhwali Folk Dance",
        history: "Known as 'Devbhumi' (Land of the Gods), it holds deep significance in Hindu mythology and is the origin of the Ganga and Yamuna rivers.",
        specialties: "Aipan art, ringal (bamboo) craft, and woolen handlooms.",
        traditions: "The mesmerizing Ganga Aarti, Kumbh Mela at Haridwar, and Langvir Nritya.",
        clothing: "Women wear a Ghagri (skirt) with an Odhni (Pichora), while men wear Kurta, Pyjama, and a Jawahar Topi."
    },
    "IN-WB": {
        name: "West Bengal",
        capital: "Kolkata",
        language: "Bengali",
        food: "Rosogolla, Macher Jhol, Sandesh",
        places: "Victoria Memorial, Sundarbans, Darjeeling",
        culture: "Durga Puja, Rabindra Sangeet",
        history: "A major center of the Indian independence movement and the former capital of British India.",
        specialties: "Terracotta art of Bishnupur, Baluchari sarees, and Kantha embroidery.",
        traditions: "The grand, artistic celebrations of Durga Puja and Baul folk music.",
        clothing: "Men traditionally wear a white Dhoti and Panjabi (kurta), while women wear sarees, often draped in the classic Bengali style."
    }
};
